name: Run Agentic Red Team Pentests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  security-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout CI/CD demo repository
        uses: actions/checkout@v4

      - name: Checkout AgentArx repository
        uses: actions/checkout@v4
        with:
          repository: AgentArx/AgentArx
          path: agentarx-repo
          
      - name: Copy AgentArx files to workspace
        run: |
          cp -r agentarx-repo/src .
          cp -r agentarx-repo/attack_scenarios .
          cp agentarx-repo/requirements.txt .

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure environment
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # Create .env file with required configuration
          cat > .env << EOF
          OPENAI_API_KEY=${OPENAI_API_KEY}
          OPENAI_MODEL=gpt-5-nano
          LLM_TEMPERATURE=0
          MAX_COMPLETION_TOKENS=18000
          REPORTER_TYPE=local
          MAX_RECON_LLM_CALLS=1
          MAX_ATTACK_LLM_CALLS=1
          MAX_COOPERATIVE_ITERATIONS=1
          REQUEST_TIMEOUT_OPENAI=120
          REQUEST_TIMEOUT_TARGET_SYSTEM=30
          EXECUTION_LOGGING=true
          LOG_PROMPTS=true
          LOG_COMPLETIONS=true
          LOG_TOOL_CALLS=true
          WEB_HOST=127.0.0.1
          WEB_PORT=5000
          EOF
          
          # Create target_config.json with Google Gruyere target
          mkdir -p src/agentarx/config
          cat > src/agentarx/config/target_config.json << EOF
          {
            "target_id": "google_gruyere_001",
            "name": "Google Gruyere Test Target",
            "network": {
              "url": "https://google-gruyere.appspot.com",
              "host": "google-gruyere.appspot.com",
              "port": 443
            }
          }
          EOF

      - name: Run AgentArx security test
        env:
          PYTHONPATH: src
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: gpt-5-nano
          LLM_TEMPERATURE: 0
          MAX_COMPLETION_TOKENS: 18000
          MAX_RECON_LLM_CALLS: 1
          MAX_ATTACK_LLM_CALLS: 1
          MAX_COOPERATIVE_ITERATIONS: 1
          REPORTER_TYPE: local
          REQUEST_TIMEOUT_OPENAI: 120
          EXECUTION_LOGGING: true
        run: |
          python -m agentarx.main --file ./attack_scenarios/MAS_2025_00001__Prompt_Inject_Data_Leakage.json
        timeout-minutes: 15
        continue-on-error: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: agentarx-results
          path: |
            results/
            logs/
          retention-days: 30
      
      - name: Check for test results
        if: always()
        run: |
          if [ -d "results" ] && [ "$(ls -A results)" ]; then
            echo "✅ Test results generated"
            ls -la results/
          else
            echo "⚠️ No results generated - test may have failed early"
          fi
